apiVersion: v1
kind: Service
metadata:
  name: netspeak-server
spec:
  type: NodePort
  selector:
    app: netspeak-server
  ports:
    - nodePort: 32400
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netspeak-index-pvc
  labels:
    app: netspeak-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 350Gi
  storageClassName: ceph-rbd

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netspeak-server
spec:
  selector:
    matchLabels:
      app: netspeak-server
  replicas: 1
  template:
    metadata:
      labels:
        app: netspeak-server
    spec:
      containers:
      - name: netspeak-server
        image: webis/netspeak:4.0.1
        command: ['sh', '-c', 'export CEPH_LOG_DIR="/netspeak-logs/started-at-$(date +%s)-on-host-$(hostname)" && mkdir -p ${CEPH_LOG_DIR} && ln -s ${CEPH_LOG_DIR} /var/log/netspeak && catalina.sh run']
        volumeMounts:
        - mountPath: "/netspeak-data"
          name: netspeak-working-index
          readOnly: false
        - mountPath: "/netspeak-logs/"
          name: netspeak-logs
          readOnly: false
      initContainers:
      - name: copy-resources
        image: eeacms/rsync:2.3
        command: ['sh', '-c', "rsync -a /src/netspeak4* /target"]
        volumeMounts:
        - mountPath: "/src/"
          name: netspeak-data-in-production
          readOnly: true
        - mountPath: "/target/"
          name: netspeak-working-index
          readOnly: false
      volumes:
      - name: netspeak-data-in-production
        hostPath:
          path: /mnt/ceph/storage/data-in-production/data-research/netspeak/
          type: Directory
      - name: netspeak-logs
        hostPath:
          path: /mnt/ceph/storage/data-in-progress/data-research/netspeak/logs/netspeak4-kubernetes/
          type: Directory
      - name: netspeak-working-index
        persistentVolumeClaim:
            claimName: netspeak-index-pvc

